### ISSUE TITLE
Integrate translations

### ISSUE THREAD

**Issue by NioDeBacker** [HOGENT-IT-Lab/HOGENT-IT-Lab.github.io#4]
Add and configure [next-i18next]( https://github.com/i18next/next-i18next ).
Translate website to both NL and EN

**Comment by TieProost** [comment]
Voor zover ik begrijp gaat [next-i18next](https://github.com/i18next/next-i18next) niet werken met github pages.
Omdat de action een static build maakt, werkt server-side rendering en de "interne api" in /pages niet.

Correct me if I'm wrong want ik heb niet zoveel ervaring met next.js :)

Bij het proberen runnen van app:
```Error: Specified "i18n" cannot be used with "output: export". See more info here: https://nextjs.org/docs/messages/export-no-i18n```

Deel van de build action - static export:
![image](https://user-images.githubusercontent.com/100168771/233604481-d3dfa473-ec8f-4cf3-a9f1-55ffb65486ff.png)


EDIT: ik zal als alternatief react-i18next gebruiken
